set(CMAKE_SYSTEM_NAME WINDOWS)
set(CMAKE_SYSTEM_PROCESSOR AMD64)

if(UNIX)
	set(CMAKE_C_COMPILER "/bin/gcc")
	set(CMAKE_CXX_COMPILER "/bin/clang++")
elseif(WIN32)
	set(CMAKE_C_COMPILER "cl.exe")
	set(CMAKE_CXX_COMPILER "cl.exe")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)